# database/tags.py
"""
Tag configuration for ISBM SCADA system.
Uses templates per machine type -- define tags once, expand per machine.
"""

OPC_SERVER_URL = "opc.tcp://localhost:52250"

# -- Tag Templates -----------------------------------------------------------
# {m} is replaced with the OPC name prefix (e.g., "Machine 1")

TAG_TEMPLATES = {
    "70DPW": {
        "Auto Cycle": "ns=2;s={m}.Auto Cycle",
        "Main Ram FW Pressure": "ns=2;s={m}.Main RAM FW Pressure",
        "Stretch Unit UP FA Pressure": "ns=2;s={m}.Stretch Unit UP FA Preesure",
        "Blow Mold CL FA Pressure": "ns=2;s={m}.Blow Mold CL FA Pressure",
        "Injection Time": "ns=2;s={m}.Injection Time",
        "Cooling Time": "ns=2;s={m}.Cooling Time",
        "Stretch Time": "ns=2;s={m}.Stretch Time",
        "Blow Time": "ns=2;s={m}.Blow Time",
        "Primary Blow Time A": "ns=2;s={m}.Primary Blow Time A",
        "Primary Blow Time B": "ns=2;s={m}.Primary Blow Time B",
        "Secondary Blow Time A": "ns=2;s={m}.Secondary Blow Time A",
        "Secondary Blow Time B": "ns=2;s={m}.Secondary Blow Time B",
        "P-V SV": "ns=2;s={m}.P-V SV",
        "Shot Size SV": "ns=2;s={m}.Shot Size SV",
        "Screw Set Data 1 Pressure": "ns=2;s={m}.Screw Set Data 1 Pressure",
        "Screw Set Data 2 Pressure": "ns=2;s={m}.Screw Set Data 2 Pressure",
        "Barrel Rear Front SV": "ns=2;s={m}.Barrel Rear Front SV",
        "Barrel Middle SV": "ns=2;s={m}.Barrel Middle SV",
        "Barrel Front SV": "ns=2;s={m}.Barrel Front SV",
        "Barrel Nozzle SV": "ns=2;s={m}.Barrel Nozzle SV",
        "HR Block 1 SV": "ns=2;s={m}.HR Block 1 SV",
        "HR Block 2 SV": "ns=2;s={m}.HR Block 2 SV",
        "HR Block 3 SV": "ns=2;s={m}.HR Block 3 SV",
        "HR Block 4 SV": "ns=2;s={m}.HR Block 4 SV",
        "Barrel Rear Rear SV": "ns=2;s={m}.Barrel Rear Rear SV",
        "HR Sprue SV": "ns=2;s={m}.HR Sprue SV",
        "Oil Temperature SV": "ns=2;s={m}.Oil Temperature SV",
        "HR Nozzle 1 SV": "ns=2;s={m}.HR Nozzle 1 SV",
        "HR Nozzle 2 SV": "ns=2;s={m}.HR Nozzle 2 SV",
        "HR Nozzle 3 SV": "ns=2;s={m}.HR Nozzle 3 SV",
        "HR Nozzle 4 SV": "ns=2;s={m}.HR Nozzle 4 SV",
        "HR Nozzle 5 SV": "ns=2;s={m}.HR Nozzle 5 SV",
        "HR Nozzle 6 SV": "ns=2;s={m}.HR Nozzle 6 SV",
        "HR Nozzle 7 SV": "ns=2;s={m}.HR Nozzle 7 SV",
        "HR Nozzle 8 SV": "ns=2;s={m}.HR Nozzle 8 SV",
        "HR Nozzle 9 SV": "ns=2;s={m}.HR Nozzle 9 SV",
        "HR Nozzle 10 SV": "ns=2;s={m}.HR Nozzle 10 SV",
        "HR Nozzle 11 SV": "ns=2;s={m}.HR Nozzle 11 SV",
        "HR Nozzle 12 SV": "ns=2;s={m}.HR Nozzle 12 SV",
        "HR Nozzle 13 SV": "ns=2;s={m}.HR Nozzle 13 SV",
        "HR Nozzle 14 SV": "ns=2;s={m}.HR Nozzle 14 SV",
        "HR Nozzle 15 SV": "ns=2;s={m}.HR Nozzle 15 SV",
        "HR Nozzle 16 SV": "ns=2;s={m}.HR Nozzle 16 SV",
        "HR Nozzle 17 SV": "ns=2;s={m}.HR Nozzle 17 SV",
        "HR Nozzle 18 SV": "ns=2;s={m}.HR Nozzle 18 SV",
        "HR Nozzle 19 SV": "ns=2;s={m}.HR Nozzle 19 SV",
        "HR Nozzle 20 SV": "ns=2;s={m}.HR Nozzle 20 SV",
        "HR Nozzle 21 SV": "ns=2;s={m}.HR Nozzle 21 SV",
        "HR Nozzle 22 SV": "ns=2;s={m}.HR Nozzle 22 SV",
        "HR Nozzle 23 SV": "ns=2;s={m}.HR Nozzle 23 SV",
        "HR Nozzle 24 SV": "ns=2;s={m}.HR Nozzle 24 SV",
        "H Pot 1 SV": "ns=2;s={m}.H Pot 1 SV",
        "H Pot 2 SV": "ns=2;s={m}.H Pot 2 SV",
        "H Pot 3 SV": "ns=2;s={m}.H Pot 3 SV",
        "H Pot 4 SV": "ns=2;s={m}.H Pot 4 SV",
        "H Pot 5 SV": "ns=2;s={m}.H Pot 5 SV",
        "H Pot 6 SV": "ns=2;s={m}.H Pot 6 SV",
        "H Pot 7 SV": "ns=2;s={m}.H Pot 7 SV",
        "H Pot 8 SV": "ns=2;s={m}.H Pot 8 SV",
        "H Pot 9 SV": "ns=2;s={m}.H Pot 9 SV",
        "H Pot 10 SV": "ns=2;s={m}.H Pot 10 SV",
        "H Pot 11 SV": "ns=2;s={m}.H Pot 11 SV",
        "H Pot 12 SV": "ns=2;s={m}.H Pot 12 SV",
        "H Pot 13 SV": "ns=2;s={m}.H Pot 13 SV",
        "H Pot 14 SV": "ns=2;s={m}.H Pot 14 SV",
        "H Pot 15 SV": "ns=2;s={m}.H Pot 15 SV",
        "H Pot 16 SV": "ns=2;s={m}.H Pot 16 SV",
        "H Pot 17 SV": "ns=2;s={m}.H Pot 17 SV",
        "H Pot 18 SV": "ns=2;s={m}.H Pot 18 SV",
        "H Pot 19 SV": "ns=2;s={m}.H Pot 19 SV",
        "H Pot 20 SV": "ns=2;s={m}.H Pot 20 SV",
        "H Pot 21 SV": "ns=2;s={m}.H Pot 21 SV",
        "H Pot 22 SV": "ns=2;s={m}.H Pot 22 SV",
        "H Pot 23 SV": "ns=2;s={m}.H Pot 23 SV",
        "H Pot 24 SV": "ns=2;s={m}.H Pot 24 SV",
        "H Pot 25 SV": "ns=2;s={m}.H Pot 25 SV",
        "H Pot 26 SV": "ns=2;s={m}.H Pot 26 SV",
        "H Pot 27 SV": "ns=2;s={m}.H Pot 27 SV",
        "H Pot 28 SV": "ns=2;s={m}.H Pot 28 SV",
        "H Pot 29 SV": "ns=2;s={m}.H Pot 29 SV",
        "H Pot 30 SV": "ns=2;s={m}.H Pot 30 SV",
        "H Pot 31 SV": "ns=2;s={m}.H Pot 31 SV",
        "H Pot 32 SV": "ns=2;s={m}.H Pot 32 SV",
        "H Pot 33 SV": "ns=2;s={m}.H Pot 33 SV",
        "H Pot 34 SV": "ns=2;s={m}.H Pot 34 SV",
        "H Pot 35 SV": "ns=2;s={m}.H Pot 35 SV",
        "H Pot 36 SV": "ns=2;s={m}.H Pot 36 SV",
        "H Pot 37 SV": "ns=2;s={m}.H Pot 37 SV",
        "H Pot 38 SV": "ns=2;s={m}.H Pot 38 SV",
        "H Pot 39 SV": "ns=2;s={m}.H Pot 39 SV",
        "H Pot 40 SV": "ns=2;s={m}.H Pot 40 SV",
        "Production Quantity": "ns=2;s={m}.Production Quantity",
        "Screw Position": "ns=2;s={m}.Screw Position",
        "Screw Pressure Monitor": "ns=2;s={m}.Screw Pressure Monitor",
        "Cycle Time": "ns=2;s={m}.Cycle Time",
        "V-P Time PV": "ns=2;s={m}.V-P Time PV",
        "Charge Time": "ns=2;s={m}.Charge Time",
        "Injection Mold CL FA": "ns=2;s={m}.Injection Mold CL FA",
        "Injection Mold OP FA": "ns=2;s={m}.Injection Mold OP FA",
        "Lip Mold CL FA": "ns=2;s={m}.Lip Mold CL FA",
        "Lip Mold OP FA": "ns=2;s={m}.Lip Mold OP FA",
        "Blow Mold CL FA": "ns=2;s={m}.Blow Mold CL FA",
        "Blow Mold OP FA": "ns=2;s={m}.Blow Mold OP FA",
        "Injection Mold CL": "ns=2;s={m}.Injection Mold CL",
        "Injection Mold OP": "ns=2;s={m}.Injection Mold OP",
        "Blow Core DW": "ns=2;s={m}.Blow Core DW",
        "Blow Core UP": "ns=2;s={m}.Blow Core UP",
        "Bottom UP": "ns=2;s={m}.Bottom UP",
        "Bottom DW": "ns=2;s={m}.Bottom DW",
        "Blow Mold CL": "ns=2;s={m}.Blow Mold CL",
        "Blow Mold OP": "ns=2;s={m}.Blow Mold OP",
        "Blow Core Hold FW": "ns=2;s={m}.Blow Core Hold FW",
        "Stretch Unit DW FA": "ns=2;s={m}.Stretch Unit DW FA",
        "Stretch Unit UP FA": "ns=2;s={m}.Stretch Unit UP FA",
        "Stretch Unit DW": "ns=2;s={m}.Stretch Unit DW",
        "Stretch Unit UP": "ns=2;s={m}.Stretch Unit UP",
        "Blow Mold M": "ns=2;s={m}.Blow Mold M",
        "Blow Mold C": "ns=2;s={m}.Blow Mold C",
        "Dry Cycle Time": "ns=2;s={m}.Dry Cycle Time",
        "Barrel Rear Front PV": "ns=2;s={m}.Barrel Rear Front PV",
        "Barrel Middle PV": "ns=2;s={m}.Barrel Middle PV",
        "Barrel Front PV": "ns=2;s={m}.Barrel Front PV",
        "Barrel Nozzle PV": "ns=2;s={m}.Barrel Nozzle PV",
        "HR Block 1 PV": "ns=2;s={m}.HR Block 1 PV",
        "HR Block 2 PV": "ns=2;s={m}.HR Block 2 PV",
        "HR Block 3 PV": "ns=2;s={m}.HR Block 3 PV",
        "HR Block 4 PV": "ns=2;s={m}.HR Block 4 PV",
        "Barrel Rear Rear PV": "ns=2;s={m}.Barrel Rear Rear PV",
        "HR Sprue PV": "ns=2;s={m}.HR Sprue PV",
        "Oil Temperature PV": "ns=2;s={m}.Oil Temperature PV",
        "HR Nozzle 1 PV": "ns=2;s={m}.HR Nozzle 1 PV",
        "HR Nozzle 2 PV": "ns=2;s={m}.HR Nozzle 2 PV",
        "HR Nozzle 3 PV": "ns=2;s={m}.HR Nozzle 3 PV",
        "HR Nozzle 4 PV": "ns=2;s={m}.HR Nozzle 4 PV",
        "HR Nozzle 5 PV": "ns=2;s={m}.HR Nozzle 5 PV",
        "HR Nozzle 6 PV": "ns=2;s={m}.HR Nozzle 6 PV",
        "HR Nozzle 7 PV": "ns=2;s={m}.HR Nozzle 7 PV",
        "HR Nozzle 8 PV": "ns=2;s={m}.HR Nozzle 8 PV",
        "HR Nozzle 9 PV": "ns=2;s={m}.HR Nozzle 9 PV",
        "HR Nozzle 10 PV": "ns=2;s={m}.HR Nozzle 10 PV",
        "HR Nozzle 11 PV": "ns=2;s={m}.HR Nozzle 11 PV",
        "HR Nozzle 12 PV": "ns=2;s={m}.HR Nozzle 12 PV",
        "HR Nozzle 13 PV": "ns=2;s={m}.HR Nozzle 13 PV",
        "HR Nozzle 14 PV": "ns=2;s={m}.HR Nozzle 14 PV",
        "HR Nozzle 15 PV": "ns=2;s={m}.HR Nozzle 15 PV",
        "HR Nozzle 16 PV": "ns=2;s={m}.HR Nozzle 16 PV",
        "HR Nozzle 17 PV": "ns=2;s={m}.HR Nozzle 17 PV",
        "HR Nozzle 18 PV": "ns=2;s={m}.HR Nozzle 18 PV",
        "HR Nozzle 19 PV": "ns=2;s={m}.HR Nozzle 19 PV",
        "HR Nozzle 20 PV": "ns=2;s={m}.HR Nozzle 20 PV",
        "HR Nozzle 21 PV": "ns=2;s={m}.HR Nozzle 21 PV",
        "HR Nozzle 22 PV": "ns=2;s={m}.HR Nozzle 22 PV",
        "HR Nozzle 23 PV": "ns=2;s={m}.HR Nozzle 23 PV",
        "HR Nozzle 24 PV": "ns=2;s={m}.HR Nozzle 24 PV",
        "H Pot 1 PV": "ns=2;s={m}.H Pot 1 PV",
        "H Pot 2 PV": "ns=2;s={m}.H Pot 2 PV",
        "H Pot 3 PV": "ns=2;s={m}.H Pot 3 PV",
        "H Pot 4 PV": "ns=2;s={m}.H Pot 4 PV",
        "H Pot 5 PV": "ns=2;s={m}.H Pot 5 PV",
        "H Pot 6 PV": "ns=2;s={m}.H Pot 6 PV",
        "H Pot 7 PV": "ns=2;s={m}.H Pot 7 PV",
        "H Pot 8 PV": "ns=2;s={m}.H Pot 8 PV",
        "H Pot 9 PV": "ns=2;s={m}.H Pot 9 PV",
        "H Pot 10 PV": "ns=2;s={m}.H Pot 10 PV",
        "H Pot 11 PV": "ns=2;s={m}.H Pot 11 PV",
        "H Pot 12 PV": "ns=2;s={m}.H Pot 12 PV",
        "H Pot 13 PV": "ns=2;s={m}.H Pot 13 PV",
        "H Pot 14 PV": "ns=2;s={m}.H Pot 14 PV",
        "H Pot 15 PV": "ns=2;s={m}.H Pot 15 PV",
        "H Pot 16 PV": "ns=2;s={m}.H Pot 16 PV",
        "H Pot 17 PV": "ns=2;s={m}.H Pot 17 PV",
        "H Pot 18 PV": "ns=2;s={m}.H Pot 18 PV",
        "H Pot 19 PV": "ns=2;s={m}.H Pot 19 PV",
        "H Pot 20 PV": "ns=2;s={m}.H Pot 20 PV",
        "H Pot 21 PV": "ns=2;s={m}.H Pot 21 PV",
        "H Pot 22 PV": "ns=2;s={m}.H Pot 22 PV",
        "H Pot 23 PV": "ns=2;s={m}.H Pot 23 PV",
        "H Pot 24 PV": "ns=2;s={m}.H Pot 24 PV",
        "H Pot 25 PV": "ns=2;s={m}.H Pot 25 PV",
        "H Pot 26 PV": "ns=2;s={m}.H Pot 26 PV",
        "H Pot 27 PV": "ns=2;s={m}.H Pot 27 PV",
        "H Pot 28 PV": "ns=2;s={m}.H Pot 28 PV",
        "H Pot 29 PV": "ns=2;s={m}.H Pot 29 PV",
        "H Pot 30 PV": "ns=2;s={m}.H Pot 30 PV",
        "H Pot 31 PV": "ns=2;s={m}.H Pot 31 PV",
        "H Pot 32 PV": "ns=2;s={m}.H Pot 32 PV",
        "H Pot 33 PV": "ns=2;s={m}.H Pot 33 PV",
        "H Pot 34 PV": "ns=2;s={m}.H Pot 34 PV",
        "H Pot 35 PV": "ns=2;s={m}.H Pot 35 PV",
        "H Pot 36 PV": "ns=2;s={m}.H Pot 36 PV",
        "H Pot 37 PV": "ns=2;s={m}.H Pot 37 PV",
        "H Pot 38 PV": "ns=2;s={m}.H Pot 38 PV",
        "H Pot 39 PV": "ns=2;s={m}.H Pot 39 PV",
        "H Pot 40 PV": "ns=2;s={m}.H Pot 40 PV",
    },
    # Placeholder templates for future machine types
    "150DP": {},
    "Chiller": {},
    "Compressor": {},
    "Dryer": {},
}

# -- Machine Registry -------------------------------------------------------
# machine_id -> type + OPC name prefix

MACHINE_REGISTRY = {
    1: {"type": "70DPW", "opc_name": "Machine 1"},
    22: {"type": "70DPW", "opc_name": "Machine 22"},
    23: {"type": "70DPW", "opc_name": "Machine 23"},
    24: {"type": "70DPW", "opc_name": "Machine 24"},
    25: {"type": "70DPW", "opc_name": "Machine 25"},
    26: {"type": "70DPW", "opc_name": "Machine 26"},
    59: {"type": "70DPW", "opc_name": "Machine 59"},
    60: {"type": "70DPW", "opc_name": "Machine 60"},
    61: {"type": "70DPW", "opc_name": "Machine 61"},
    62: {"type": "70DPW", "opc_name": "Machine 62"},
    68: {"type": "70DPW", "opc_name": "Machine 68"},
}


def get_machine_tags(machine_id: int) -> dict:
    """Build the full tag dict for a machine by applying its template."""
    info = MACHINE_REGISTRY[machine_id]
    template = TAG_TEMPLATES[info["type"]]
    return {
        tag_name: node_id.format(m=info["opc_name"])
        for tag_name, node_id in template.items()
    }


def get_machine_type(machine_id: int) -> str:
    """Return the machine type string for a given machine ID."""
    return MACHINE_REGISTRY[machine_id]["type"]


def get_machines_by_type(machine_type: str) -> list[int]:
    """Return all machine IDs of a given type."""
    return [mid for mid, info in MACHINE_REGISTRY.items() if info["type"] == machine_type]


# -- Backward Compatibility --------------------------------------------------
# Existing code uses MACHINES[60]["Cycle Time"] -- this still works
MACHINES = {mid: get_machine_tags(mid) for mid in MACHINE_REGISTRY}
